-- MySQL Script generated by MySQL Workbench
-- Sat Feb 26 09:45:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GHP2021
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GHP2021
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GHP2021` DEFAULT CHARACTER SET utf8 ;
USE `GHP2021` ;

-- -----------------------------------------------------
-- Table `GHP2021`.`POST_INFORMATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GHP2021`.`POST_INFORMATION` (
  `ID` BIGINT NOT NULL,
  `TIME` DATETIME(3) NOT NULL,
  `LATITUDE` VARCHAR(45) NULL,
  `LONGITUDE` VARCHAR(45) NULL,
  `INFORMATION` VARCHAR(255) NULL,
  `APPROVED` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GHP2021`.`FILE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GHP2021`.`FILE` (
  `ID` BIGINT NOT NULL,
  `FILE` MEDIUMBLOB NOT NULL COMMENT 'ファイル',
  PRIMARY KEY (`ID`),
  INDEX `fk_FILE_POST_INFORMATION1_idx` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_FILE_POST_INFORMATION1`
    FOREIGN KEY (`ID`)
    REFERENCES `GHP2021`.`POST_INFORMATION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GHP2021`.`SHELTER_INFORMATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GHP2021`.`SHELTER_INFORMATION` (
  `GEOM` VARCHAR(255) NOT NULL,
  `ADMINISTRATIVE_AREA_CODE` VARCHAR(45) NOT NULL COMMENT '行政区域コード\n（P20_001）',
  `NAME` VARCHAR(255) NOT NULL COMMENT '名称\n（P20_002）',
  `ADDRESS` VARCHAR(255) NOT NULL COMMENT '住所\n（P20_003）',
  `TYPE` VARCHAR(45) NOT NULL,
  `LATITUDE` DOUBLE NOT NULL COMMENT '緯度\n（緯度）',
  `LONGITUDE` DOUBLE NOT NULL COMMENT '経度\n（経度）',
  `P20_007` TINYINT NOT NULL COMMENT '地震災害\n（P20_007）',
  `P20_008` TINYINT NOT NULL COMMENT '津波災害\n（P20_008）',
  `P20_009` TINYINT NOT NULL COMMENT '水害\n（P20_009）',
  `P20_010` TINYINT NOT NULL COMMENT '火山災害\n（P20_010）',
  `P20_011` TINYINT NOT NULL COMMENT 'その他\n（P20_011）',
  `P20_012` TINYINT NOT NULL COMMENT '指定なし\n（P20_012）',
  PRIMARY KEY (`GEOM`))
ENGINE = InnoDB
COMMENT = 'https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-P20.html\n\n災害対策基本法に基づき都道府県及び市町村により作成された地域防災計画に示される避難施設';


-- -----------------------------------------------------
-- Table `GHP2021`.`SHELTER_INFORMATION_EXT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GHP2021`.`SHELTER_INFORMATION_EXT` (
  `GEOM` VARCHAR(255) NOT NULL,
  `OPEN` TINYINT NOT NULL DEFAULT 0 COMMENT '0:閉鎖中\n1:開所',
  `COMMENT` VARCHAR(255) NULL COMMENT 'コメント',
  PRIMARY KEY (`GEOM`),
  INDEX `fk_SHELTER_INFORMATION_SHELTER_INFORMATION_idx` (`GEOM` ASC) VISIBLE,
  CONSTRAINT `fk_SHELTER_INFORMATION_SHELTER_INFORMATION`
    FOREIGN KEY (`GEOM`)
    REFERENCES `GHP2021`.`SHELTER_INFORMATION` (`GEOM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
