FROM payara/server-full:5.2022.1

COPY mysql-connector-java-8.0.22.jar /opt/payara/appserver/glassfish/domains/domain1/lib
COPY setup_payara.sh /opt/payara/setup_payara.sh
COPY glassfish-resources.xml /opt/payara/glassfish-resources.xml
COPY glassfish-resources2.xml /opt/payara/glassfish-resources2.xml
COPY log4j2.xml /opt/payara/log4j2.xml
RUN mkdir /opt/payara/logs
