FROM payara/server-full:5.2022.1

COPY mysql-connector-java-8.0.22.jar /opt/payara/appserver/glassfish/domains/domain1/lib
COPY setup_payara.sh /setup_payara.sh
COPY glassfish-resources.xml /glassfish-resources.xml
COPY GHP2021App.ear /GHP2021App.ear
#RUN chmod +x /setup_payara.sh